-- CREATE TABLE IF NOT EXISTS departments (
--     department_id BIGINT NOT NULL AUTO_INCREMENT,
--     department_name VARCHAR(50) NOT NULL,
--
--     PRIMARY KEY (department_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- CREATE TABLE IF NOT EXISTS certifications (
--     certification_id BIGINT NOT NULL AUTO_INCREMENT,
--     certification_name VARCHAR(50) NOT NULL,
--     certification_level INT NOT NULL,
--
--     PRIMARY KEY (certification_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- CREATE TABLE IF NOT EXISTS employees (
--     employee_id BIGINT NOT NULL AUTO_INCREMENT,
--     department_id BIGINT NOT NULL,
--
--     employee_name VARCHAR(100) NOT NULL,
--     employee_name_kana VARCHAR(255),
--
--     employee_birth_date DATE,
--     employee_email VARCHAR(50) NOT NULL,
--     employee_telephone VARCHAR(50),
--
--     employee_login_id VARCHAR(50) NOT NULL,
--     employee_login_password VARCHAR(100) DEFAULT NULL,
--
--     employee_role VARCHAR(20) NOT NULL,
--
--     PRIMARY KEY (employee_id),
--
--     CONSTRAINT fk_employee_department
--         FOREIGN KEY (department_id)
--         REFERENCES departments (department_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- CREATE TABLE IF NOT EXISTS employees_certifications (
--     employee_certification_id BIGINT NOT NULL AUTO_INCREMENT,
--
--     employee_id BIGINT NOT NULL,
--     certification_id BIGINT NOT NULL,
--
--     start_date DATE NOT NULL,
--     end_date DATE,
--
--     score DECIMAL(5,2),
--
--     PRIMARY KEY (employee_certification_id),
-- 
--     CONSTRAINT fk_emp_cert_employee
--         FOREIGN KEY (employee_id)
--         REFERENCES employees (employee_id),
--
--     CONSTRAINT fk_emp_cert_certification
--         FOREIGN KEY (certification_id)
--         REFERENCES certifications (certification_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- INSERT INTO departments (department_name)
-- VALUES
-- ('Development'),
-- ('Sales'),
-- ('Human Resource');
--
-- INSERT INTO certifications (
--     certification_name,
--     certification_level
-- )
-- VALUES
-- ('JLPT N1', 1),
-- ('JLPT N2', 2),
-- ('JLPT N3', 3),
-- ('JLPT N4', 4),
-- ('JLPT N5', 5);
--
-- INSERT INTO employees (
--     department_id,
--     employee_name,
--     employee_name_kana,
--     employee_birth_date,
--     employee_email,
--     employee_telephone,
--     employee_login_id,
--     employee_login_password,
--     employee_role
-- )
-- VALUES (
--     1,
--     'Administrator',
--     'アドミニストレーター',
--     '1990-01-01',
--     'la@luvina.net',
--     '0900000000',
--     'admin',
--     '$2a$10$r.XIN4K9vTioiuYQwaTop.UVQ5r5FvrKk2V5Orm9Hc6n4i9Tvjthy',
--     'ADMIN'
-- );
--
-- INSERT INTO employees_certifications (
--     employee_id,
--     certification_id,
--     start_date,
--     end_date,
--     score
-- )
-- VALUES (
--     1,
--     2,
--     '2024-01-01',
--     '2026-01-01',
--     180.00
-- );
--
